### ISSUE TITLE
Akeneo5 upgrade

### ISSUE THREAD

**Issue by Trogie** [trilix-gmbh/akeneo-events-api-bundle#16]
Hello Trilix gmbh,

Are there any plans to upgrade the bundle to the Akeneo v5?

**Comment by flagbird** [comment]
The Akeneo 5 Event API might replace the Trillix one in the future, but it currently only supports product, product models and variants. Some limitations are an extra for the Akeneo one, so the need to keep Trillix Event API alive would be much appreciated.

**Comment by psw1986** [comment]
Hello @Trogie,

Events API was updated to support Akeneo PIM 5.x version. Version 0.7.0 is available now.

**Comment by psw1986** [comment]
> The Akeneo 5 Event API might replace the Trillix one in the future, but it currently only supports product, product models and variants. Some limitations are an extra for the Akeneo one, so the need to keep Trillix Event API alive would be much appreciated.

Hello @flagbird, you are right!
As for now, Events API is updated to support Akeneo PIM 5.
